spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportswear
    username: root
    password: Thanh12052002!
  payment:
    vn-pay:
      url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      tmn-code: AD6VIAPZ
      secretKey: 2Y1BOE79DWMZGOUXRXYY8TJ3SW6MWMD2
      return-url: http://localhost:8080/api/v1/payment/vn-pay-callback
      version: 2.1.0
      command: pay
      order-type: other
  mvc:
    favicon:
      enabled=false:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  app:
    jwtSecret: cQdiKaMYsvXaFkwz32/IhA==
    jwtExpirationMs: 86400000
  redis:
    host: localhost      # Địa chỉ Redis, mặc định là localhost
    port: 6379           # Cổng Redis, mặc định là 6379
server:
  address: 0.0.0.0  # Cho phép kết nối từ mọi IP
  port: 8080        # Cổng mà ứng dụng sẽ lắng nghe
